dbPath: /Users/allan/src/boliaSofa/searches.tinydb.json
pushBulletId: o.B8s0B7VUNVgrzU4fNpvTjan4VKPO6qhJ
urls: [
  'http://www.dba.dk/til-boligen/spise-og-dagligstuemoebler/sofaer-og-sofagrupper/produkt-chaiselong/stoerrelse-4-pers/reg-koebenhavn-og-omegn/?soeg=bolia&produkt=hjoernesofa&produkt=sofagruppe&stoerrelse=5-pers&stoerrelse=6-pers&fra=privat',
  'http://www.dba.dk/computer-og-spillekonsoller/hardware-og-software/tastaturer-og-mus/?soeg=cherry+mx&fra=privat',
  'http://www.dba.dk/til-boligen/spise-og-dagligstuemoebler/sofaborde-og-andre-borde/produkt-sofabord/reg-koebenhavn-og-omegn/?soeg=nova&sort=listingdate-desc&iswildcard&fra=privat',
  'http://www.dba.dk/til-boligen/spise-og-dagligstuemoebler/reg-koebenhavn-og-omegn/?soeg=bordstel&fra=privat',
  'http://www.dba.dk/til-boligen/spise-og-dagligstuemoebler/reg-koebenhavn-og-omegn/?soeg=M009&fra=privat',
  'http://www.dba.dk/til-boligen/belysning/reg-koebenhavn-og-omegn/?soeg=tom+rossau&fra=privat',
  'http://www.dba.dk/soeg/reg-koebenhavn-og-omegn/?soeg=cigaren+hans+wegner&fra=privat',
  'http://www.dba.dk/til-boligen/spise-og-dagligstuemoebler/sofaborde-og-andre-borde/reg-koebenhavn-og-omegn/?soeg=st%c3%b8bejern&fra=privat',
  'http://www.dba.dk/soeg/reg-koebenhavn-og-omegn/?soeg=hay+bordbukke&fra=privat',
  'http://www.dba.dk/soeg/reg-koebenhavn-og-omegn/?soeg=hay+loop&fra=privat',
  'http://www.dba.dk/computer-og-spillekonsoller/hardware-og-software/tastaturer-og-mus/reg-koebenhavn-og-omegn/?soeg=deathadder&fra=privat&iswildcard'
]
